package org.msh.tb.test.dbgen;

/**
 * Exception generated by TokenReader
 * @author Ricardo Memoria
 *
 */
public class TokenReaderException extends Exception {
	private static final long serialVersionUID = 8283511241941157033L;

	public TokenReaderException() {
	}

	public TokenReaderException(String arg0) {
		super(arg0);
	}

	public TokenReaderException(Throwable arg0) {
		super(arg0);
	}

	public TokenReaderException(String arg0, Throwable arg1) {
		super(arg0, arg1);
	}

}
