/***************************************************************
 * 01-oct-2013
 * By MSANTOS
 * 
 * BD only!!!
 * 
 * Changes all FKs of workspace.id on update restrict to cascade
 * Equalizes the id of bangladesh workspace in bangladesh server.
****************************************************************/


ALTER TABLE `healthsystem` DROP FOREIGN KEY `FK28F57FCBB9C757E8` ;
ALTER TABLE `healthsystem` 
  ADD CONSTRAINT `FK28F57FCBB9C757E8`
  FOREIGN KEY (`WORKSPACE_ID` )
  REFERENCES `workspace` (`id` )
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE `laboratory` DROP FOREIGN KEY `FK2FD84BD3B9C757E8` ;
ALTER TABLE `laboratory` 
  ADD CONSTRAINT `FK2FD84BD3B9C757E8`
  FOREIGN KEY (`WORKSPACE_ID` )
  REFERENCES `workspace` (`id` )
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE `patient` DROP FOREIGN KEY `FK340C82E5B9C757E8` ;
ALTER TABLE `patient` 
  ADD CONSTRAINT `FK340C82E5B9C757E8`
  FOREIGN KEY (`WORKSPACE_ID` )
  REFERENCES `workspace` (`id` )
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE `sequenceinfo` DROP FOREIGN KEY `FK39EADC2FB9C757E8` ;
ALTER TABLE `sequenceinfo` 
  ADD CONSTRAINT `FK39EADC2FB9C757E8`
  FOREIGN KEY (`WORKSPACE_ID` )
  REFERENCES `workspace` (`id` )
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE `userprofile` DROP FOREIGN KEY `FK3EFA133EB9C757E8` ;
ALTER TABLE `userprofile` 
  ADD CONSTRAINT `FK3EFA133EB9C757E8`
  FOREIGN KEY (`WORKSPACE_ID` )
  REFERENCES `workspace` (`id` )
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE `agerange` DROP FOREIGN KEY `FK59D8FB9EB9C757E8` ;
ALTER TABLE `agerange` 
  ADD CONSTRAINT `FK59D8FB9EB9C757E8`
  FOREIGN KEY (`WORKSPACE_ID` )
  REFERENCES `workspace` (`id` )
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE `resistancepattern` DROP FOREIGN KEY `FK606E68F7B9C757E8` ;
ALTER TABLE `resistancepattern` 
  ADD CONSTRAINT `FK606E68F7B9C757E8`
  FOREIGN KEY (`WORKSPACE_ID` )
  REFERENCES `workspace` (`id` )
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE `countrystructure` DROP FOREIGN KEY `FK7716629DB9C757E8` ;
ALTER TABLE `countrystructure` 
  ADD CONSTRAINT `FK7716629DB9C757E8`
  FOREIGN KEY (`WORKSPACE_ID` )
  REFERENCES `workspace` (`id` )
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE `userlogin` DROP FOREIGN KEY `FK8AA0DA3EB9C757E8` ;
ALTER TABLE `userlogin` 
  ADD CONSTRAINT `FK8AA0DA3EB9C757E8`
  FOREIGN KEY (`WORKSPACE_ID` )
  REFERENCES `workspace` (`id` )
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE `source` DROP FOREIGN KEY `FK93F5543BB9C757E8` ;
ALTER TABLE `source` 
  ADD CONSTRAINT `FK93F5543BB9C757E8`
  FOREIGN KEY (`WORKSPACE_ID` )
  REFERENCES `workspace` (`id` )
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE `tbunit` DROP FOREIGN KEY `FK94F2ED12B9C757E8` ;
ALTER TABLE `tbunit` 
  ADD CONSTRAINT `FK94F2ED12B9C757E8`
  FOREIGN KEY (`WORKSPACE_ID` )
  REFERENCES `workspace` (`id` )
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE `substance` DROP FOREIGN KEY `FK9709E550B9C757E8` ;
ALTER TABLE `substance` 
  ADD CONSTRAINT `FK9709E550B9C757E8`
  FOREIGN KEY (`WORKSPACE_ID` )
  REFERENCES `workspace` (`id` )
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE `fieldvalue` DROP FOREIGN KEY `FK98AC68B7B9C757E8` ;
ALTER TABLE `fieldvalue` 
  ADD CONSTRAINT `FK98AC68B7B9C757E8`
  FOREIGN KEY (`WORKSPACE_ID` )
  REFERENCES `workspace` (`id` )
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE `regimen` DROP FOREIGN KEY `FKA3F54741B9C757E8` ;
ALTER TABLE `regimen` 
  ADD CONSTRAINT `FKA3F54741B9C757E8`
  FOREIGN KEY (`WORKSPACE_ID` )
  REFERENCES `workspace` (`id` )
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE `administrativeunit` DROP FOREIGN KEY `FKA92443F2B9C757E8` ;
ALTER TABLE `administrativeunit` 
  ADD CONSTRAINT `FKA92443F2B9C757E8`
  FOREIGN KEY (`WORKSPACE_ID` )
  REFERENCES `workspace` (`id` )
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE `systemconfig` DROP FOREIGN KEY `FKC5339671B9C757E8` ;
ALTER TABLE `systemconfig` 
  ADD CONSTRAINT `FKC5339671B9C757E8`
  FOREIGN KEY (`WORKSPACE_ID` )
  REFERENCES `workspace` (`id` )
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE `medicine` DROP FOREIGN KEY `FKCE2ABA5AB9C757E8` ;
ALTER TABLE `medicine` 
  ADD CONSTRAINT `FKCE2ABA5AB9C757E8`
  FOREIGN KEY (`WORKSPACE_ID` )
  REFERENCES `workspace` (`id` )
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE `userworkspace` DROP FOREIGN KEY `FKE6C764EAB9C757E8` ;
ALTER TABLE `userworkspace` 
  ADD CONSTRAINT `FKE6C764EAB9C757E8`
  FOREIGN KEY (`WORKSPACE_ID` )
  REFERENCES `workspace` (`id` )
  ON DELETE CASCADE
  ON UPDATE CASCADE;

update workspace set id = 11 where id = 940352;
ALTER TABLE `etbmanager-bd`.`tag` CHANGE COLUMN `active` `active` TINYINT(1) NULL DEFAULT NULL  ;

