package org.msh.tb.az.entities.enums;


public enum LastAction {
	EDIT_CASE,
	CLOSE_CASE,
	RE_OPEN_CASE,
	VALIDATE_CASE,
	POST_PENDING_CASE,
	POST_ANSWER_CASE,
	TRANSFER_PATIENT_TO,
	TRANSFER_PATIENT_IN,
	TRANSFER_PATIENT_CANCEL,
	
	NEW_EXAM_HIV,
	EDIT_EXAM_HIV,
	DELETE_EXAM_HIV,
	NEW_EXAM_MICROSCOPY,
	EDIT_EXAM_MICROSCOPY,
	DELETE_EXAM_MICROSCOPY,
	NEW_EXAM_CULTURE,
	EDIT_EXAM_CULTURE,
	DELETE_EXAM_CULTURE,
	NEW_EXAM_DST,
	EDIT_EXAM_DST,
	DELETE_EXAM_DST,
	NEW_EXAM_XRAY,
	EDIT_EXAM_XRAY,
	DELETE_EXAM_XRAY,
	
	START_TREAT,
	EDIT_TREAT,
	CANCEL_TREAT,
	EDIT_CASE_DISPENSING,
	
	NEW_MED_EXAM,
	EDIT_MED_EXAM,
	DELETE_MED_EXAM,
	
	EDIT_COMORB,
	NEW_CONTACT,
	EDIT_CONTACT,
	DELETE_CONTACT,
	NEW_SIDE_EFFECT,
	EDIT_SIDE_EFFECT,
	DELETE_SIDE_EFFECT;
	
	public String getKey() {
		return "az_AZ." + getClass().getSimpleName() + "." + toString();
	}
}
