package org.msh.tb.entities;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

@Entity
@Table(name="tag")
public class Tag extends WSObject implements Serializable {
	private static final long serialVersionUID = 7625442925460611740L;

	public enum TagType { MANUAL, AUTOGEN, AUTOGEN_CONSISTENCY	}
	
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Integer id;
	
	@Column(name="tag_name", length=100)
	@NotNull
	private String name;
	
	@Lob
	private String sqlCondition; 
	
	private boolean consistencyCheck;

	
	/**
	 * Return true if tag is auto generated and maintained by the system
	 * @return
	 */
	public boolean isAutogenerated() {
		return (sqlCondition != null) && (!sqlCondition.isEmpty());
	}
	

	/**
	 * Return the tag type
	 * @return
	 */
	public TagType getType() {
		if (!isAutogenerated()) 
			return TagType.MANUAL;
		
		return (consistencyCheck? TagType.AUTOGEN_CONSISTENCY: TagType.AUTOGEN);
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the sqlCondition
	 */
	public String getSqlCondition() {
		return sqlCondition;
	}

	/**
	 * @param sqlCondition the sqlCondition to set
	 */
	public void setSqlCondition(String sqlCondition) {
		this.sqlCondition = sqlCondition;
	}

	/**
	 * @return the consistencyCheck
	 */
	public boolean isConsistencyCheck() {
		return consistencyCheck;
	}

	/**
	 * @param consistencyCheck the consistencyCheck to set
	 */
	public void setConsistencyCheck(boolean consistencyCheck) {
		this.consistencyCheck = consistencyCheck;
	}
}
