package org.msh.tb.medicines.movs;


/**
 * MovementException is the exception generated by the MovementHome class when including or removing
 * medicine movements in a unit stock. If any error with stock management (like invalid dates or 
 * trying to decrease more than it's available, for example) the system will generate this exception
 * with a message attached to it
 * @author Ricardo Memoria
 *
 */
public class MovementException extends RuntimeException {
	private static final long serialVersionUID = -3937803767842122125L;

	public MovementException(String msg) {
		super(msg);
	}
}
