package org.msh.tb.md;

/**
 * Define a warning message generated by the importing program
 * @author Ricardo Memoria
 *
 */
public class WarnMessage {
	public String id;
	public String name;
	public String description;


	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
}