/***************************************************************
* Update relationship in database 
* 
* By Ricardo Memoria - 15-feb-2011
****************************************************************/

ALTER TABLE Forecasting
 DROP FOREIGN KEY `FKC5CAEFE78A1004CB`;

ALTER TABLE Forecasting
 DROP FOREIGN KEY `FKC5CAEFE7B9C757E8`;

ALTER TABLE Forecasting
 DROP FOREIGN KEY `FKC5CAEFE7C9D89CEC`;

ALTER TABLE Forecasting
 DROP FOREIGN KEY `FKC5CAEFE7D84E76CC`;

ALTER TABLE Forecasting ADD CONSTRAINT `FKC5CAEFE78A1004CB` FOREIGN KEY `FKC5CAEFE78A1004CB` (`ADMINUNIT_ID`)
    REFERENCES AdministrativeUnit (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
 ADD CONSTRAINT `FKC5CAEFE7B9C757E8` FOREIGN KEY `FKC5CAEFE7B9C757E8` (`WORKSPACE_ID`)
    REFERENCES `Workspace` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
 ADD CONSTRAINT `FKC5CAEFE7C9D89CEC` FOREIGN KEY `FKC5CAEFE7C9D89CEC` (`TBUNIT_ID`)
    REFERENCES `Tbunit` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
 ADD CONSTRAINT `FKC5CAEFE7D84E76CC` FOREIGN KEY `FKC5CAEFE7D84E76CC` (`USER_ID`)
    REFERENCES `Sys_User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

    
ALTER TABLE ForecastingBatch
 DROP FOREIGN KEY `FKACB1CF93259FA308`;

ALTER TABLE ForecastingBatch ADD CONSTRAINT `FKACB1CF93259FA308` FOREIGN KEY `FKACB1CF93259FA308` (`FORECASTINGMEDICINE_ID`)
    REFERENCES `ForecastingMedicine` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT;
    
ALTER TABLE ForecastingCasesOnTreat
 DROP FOREIGN KEY `FK59F8823F12F7EF28`;

ALTER TABLE ForecastingCasesOnTreat
 DROP FOREIGN KEY `FK59F8823F2F370FE8`;

ALTER TABLE ForecastingCasesOnTreat ADD CONSTRAINT `FK59F8823F12F7EF28` FOREIGN KEY `FK59F8823F12F7EF28` (`FORECASTING_ID`)
    REFERENCES `Forecasting` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
 ADD CONSTRAINT `FK59F8823F2F370FE8` FOREIGN KEY `FK59F8823F2F370FE8` (`REGIMEN_ID`)
    REFERENCES `Regimen` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

ALTER TABLE ForecastingMedicine
 DROP FOREIGN KEY `FKD756D34112F7EF28`;

ALTER TABLE ForecastingMedicine
 DROP FOREIGN KEY `FKD756D341FBB4E36C`;

ALTER TABLE ForecastingMedicine ADD CONSTRAINT `FKD756D34112F7EF28` FOREIGN KEY `FKD756D34112F7EF28` (`FORECASTING_ID`)
    REFERENCES `Forecasting` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
 ADD CONSTRAINT `FKD756D341FBB4E36C` FOREIGN KEY `FKD756D341FBB4E36C` (`MEDICINE_ID`)
    REFERENCES `Medicine` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

ALTER TABLE `ForecastingNewCases`
 DROP FOREIGN KEY `FK5D8BD28A12F7EF28`;

ALTER TABLE `ForecastingNewCases` ADD CONSTRAINT `FK5D8BD28A12F7EF28` FOREIGN KEY `FK5D8BD28A12F7EF28` (`FORECASTING_ID`)
    REFERENCES `Forecasting` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

ALTER TABLE `ForecastingOrder`
 DROP FOREIGN KEY `FKAD707FA7259FA308`;

ALTER TABLE `ForecastingOrder` ADD CONSTRAINT `FKAD707FA7259FA308` FOREIGN KEY `FKAD707FA7259FA308` (`FORECASTINGMEDICINE_ID`)
    REFERENCES `ForecastingMedicine` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

ALTER TABLE `ForecastingRegimen`
 DROP FOREIGN KEY `FK9BFEF57A12F7EF28`;

ALTER TABLE `ForecastingRegimen`
 DROP FOREIGN KEY `FK9BFEF57A2F370FE8`;

ALTER TABLE `ForecastingRegimen` ADD CONSTRAINT `FK9BFEF57A12F7EF28` FOREIGN KEY `FK9BFEF57A12F7EF28` (`FORECASTING_ID`)
    REFERENCES `Forecasting` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
 ADD CONSTRAINT `FK9BFEF57A2F370FE8` FOREIGN KEY `FK9BFEF57A2F370FE8` (`REGIMEN_ID`)
    REFERENCES `Regimen` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

ALTER TABLE `ForecastingResult`
 DROP FOREIGN KEY `FK50DDAE412F7EF28`;

ALTER TABLE `ForecastingResult`
 DROP FOREIGN KEY `FK50DDAE4FBB4E36C`;

ALTER TABLE `ForecastingResult` ADD CONSTRAINT `FK50DDAE412F7EF28` FOREIGN KEY `FK50DDAE412F7EF28` (`FORECASTING_ID`)
    REFERENCES `Forecasting` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
 ADD CONSTRAINT `FK50DDAE4FBB4E36C` FOREIGN KEY `FK50DDAE4FBB4E36C` (`MEDICINE_ID`)
    REFERENCES `Medicine` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

ALTER TABLE ForecastingMedicine CHANGE COLUMN `quantityExpired` `quantityExpiredLT` INT(11) DEFAULT NULL,
 CHANGE COLUMN `stockOnOrderBeforeLeadTime` `stockOnOrderLT` INT(11) DEFAULT NULL;

update ForecastingMedicine set quantityExpiredLT=0;
