package org.msh.tb.client.shared.model;

import java.util.ArrayList;

import com.google.gwt.user.client.rpc.IsSerializable;

/**
 * Generated by the server side and sent to the client with data about 
 * the indicator table report
 * 
 * @author Ricardo Memoria
 *
 */
public class CTable implements IsSerializable {

	/**
	 * List of the top level columns
	 */
	private ArrayList<CTableColumn> columns;
	/**
	 * List of the rows with tile and its values
	 */
	private ArrayList<CTableRow> rows;
	
	/**
	 * Index of the variables used in the columns
	 */
	private int[] colVarIndex;
	
	/**
	 * Error message in case the report is not properly generated
	 */
	private String errorMessage;



	/**
	 * @return the rows
	 */
	public ArrayList<CTableRow> getRows() {
		return rows;
	}
	/**
	 * @param rows the rows to set
	 */
	public void setRows(ArrayList<CTableRow> rows) {
		this.rows = rows;
	}
	/**
	 * @return the columns
	 */
	public ArrayList<CTableColumn> getColumns() {
		return columns;
	}
	/**
	 * @param columns the columns to set
	 */
	public void setColumns(ArrayList<CTableColumn> columns) {
		this.columns = columns;
	}
	/**
	 * @return the colVarIndex
	 */
	public int[] getColVarIndex() {
		return colVarIndex;
	}
	/**
	 * @param colVarIndex the colVarIndex to set
	 */
	public void setColVarIndex(int[] colVarIndex) {
		this.colVarIndex = colVarIndex;
	}
	/**
	 * @return the errorMessage
	 */
	public String getErrorMessage() {
		return errorMessage;
	}
	/**
	 * @param errorMessage the errorMessage to set
	 */
	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}
}
